name: CI - Run Jest Tests & SonarCloud Analysis

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 #LTS  

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Generate test coverage
        run: npm test -- --coverage

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://70b8-2404-c0-5c10-00-2c3b-bdce.ngrok-free.app"
        run: | 
          sonar-scanner \
            -Dsonar.projectKey=your-project-key \
            -Dsonar.sources=src \
            -Dsonar.tests=tests \
            -Dsonar.test.inclusions="**/*.test.ts" \
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
